name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 configure_gcloud:

    runs-on: ubuntu-latest
  
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{secrets.GOOGLE_AUTH}}'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    # - name: 'Enable Gcloud api'
    #   run: gcloud iam services enable iamcredentials.googleapis.com \
    #         --project "$PROJECT_ID"
    - name: 'USE gcloud CLI'
      run: 'gcloud info'
    - name: ' Checking shit'
      run: gcloud config get compute/region
    - name: 'Get gcloud region'
      run: 'REGION=$(gcloud config get compute/region)'
    - name: 'Making sure region is here'
      run: 'gcloud auth configure-docker europe-$REGION-docker.pkg.dev'
    - name: 'Authenticate Docker and Gcloud'
      run: 'gcloud auth print-access-token --impersonate-service-account gchebodang@gmail.com | docker login -u oauth2accesstoken  --password-stdin https://$REGION-docker.pkg.dev'
    - name: 'Get gcloud region'
      run: 'REGION=$(gcloud config get compute/region)'
    - name: 'Get gcloud project'
      run: 'PROJECT=$(gcloud config get project)'
  
    
    
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: docker build . --file amd64/Dockerfile --tag $REGION-docker.pkg.dev/$PROJECT_ID/testrepo/web-counter:$(date +%s)
    - name: Push image
      run: docker push $REGION-docker.pkg.dev/$PROJECT/testrepo/web-counter:$(date +%s)
 
 # build:

 #    runs-on: ubuntu-latest

 #    steps:
    
    
  
 
