name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
 configure_gcloud:

    runs-on: ubuntu-latest
  
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{secrets.GOOGLE_AUTH}}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      
    - name: 'Authenticate Docker and Gcloud'
      run: gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://europe-central2-docker.pkg.dev

 # build_and_push_image:
 #  runs-on: ubuntu-latest
 #  needs: configure_gcloud
 #  steps:
    - uses: actions/checkout@v3
  
    - name: Build and push the Docker image
      run: docker build . --file amd64/Dockerfile --tag europe-central2-docker.pkg.dev/artful-patrol-313709/testrepo/web-counter:latest
    - name: Push image
      run: docker push europe-central2-docker.pkg.dev/artful-patrol-313709/testrepo/web-counter:latest
    
 # copy_and_run_terraform:
 #   runs-on: ubuntu-latest
 #   needs: build_and_push_image
 #   steps:
    - uses: hashicorp/setup-terraform@v2
    - name: copy file from bucket
      run: gcloud storage cp gs://artful-patrol-313709-terraform-bucket/main.tf main.tf
    - name: the fuck u think is that?
      run: terraform init
    - name: Applying changes
      run: terraform apply --auto-approve -var AUTH_TOKEN=$(gcloud auth print-access-token)
     
  
 
